name: spring-cloud-kubernetes-discoveryserver
deploymentName: spring-cloud-kubernetes-discoveryserver-deployment
replicaCount: 1
image:
  repository: springcloud/spring-cloud-kubernetes-discoveryserver
  tag: 3.2.0
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
  targetPort: 8761
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
