name: messageservice
deploymentName: messageservice-deployment
replicaCount: 1

image:
  repository: anthonysk/messageservice
  tag: 0.0.1-SNAPSHOT
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 9010
  targetPort: 9010

configMap:
  name: messageservice-config
  data:
    HOME: "/tmp"
    JAVA_TOOL_OPTIONS: "-XX:MaxRAMPercentage=75"
    SPRING_RABBITMQ_HOST: "host.docker.internal"
    SPRING_KAFKA_BOOTSTRAP_SERVERS: "host.docker.internal:39092"
    OTLP_TRACING_ENDPOINT: "http://host.docker.internal:4318/v1/traces"
    MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED: "true"

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 700Mi
