name: eurekaserver
deploymentName: eurekaserver-deployment
replicaCount: 1

image:
  repository: anthonysk/eurekaserver
  tag: 0.0.1-SNAPSHOT
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 8070
  targetPort: 8070

configMap:
  name: eurekaserver-config
  data:
    HOME: "/tmp"
    JAVA_TOOL_OPTIONS: "-XX:MaxRAMPercentage=75"
    CONFIGSERVER_HOST: "configserver"
    EUREKA_HOST: "eurekaserver"
    SPRING_RABBITMQ_HOST: "host.docker.internal"
    MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED: "true"

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 700Mi
