name: loan
deploymentName: loan-deployment
replicaCount: 2

image:
  repository: anthonysk/loan
  tag: 0.0.1-SNAPSHOT
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 8090
  targetPort: 8090

configMap:
  name: loan-config
  data:
    BPL_JVM_THREAD_COUNT: "50"
    CONFIGSERVER_HOST: "configserver"
    EUREKA_URL: "http://eurekaserver:8070/eureka/"
    CONFIGSERVER_OPTIONAL_PREFIX: ""
    SPRING_RABBITMQ_HOST: "host.docker.internal"
    SPRING_DATASOURCE_URL: "jdbc:mysql://host.docker.internal:3306/loandb"
    OTLP_TRACING_ENDPOINT: "http://host.docker.internal:4318/v1/traces"
    MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED: "true"

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 700Mi
