apiVersion: apps/v1
kind: Deployment
metadata:
  name: eurekaserver-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eurekaserver
  template:
    metadata:
      labels:
        app: eurekaserver
    spec:
      containers:
        - name: eurekaserver
          image: anthonysk/eurekaserver:0.0.1-SNAPSHOT
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8070
          envFrom:
            - configMapRef:
                name: eurekaserver-config
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 700Mi
          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            periodSeconds: 5
            failureThreshold: 24
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            periodSeconds: 10

---

apiVersion: v1
kind: Service
metadata:
  name: eurekaserver
spec:
  type: LoadBalancer
  selector:
    app: eurekaserver
  ports:
    - name: http
      port: 8070
      targetPort: http
