apiVersion: apps/v1
kind: Deployment
metadata:
  name: loan-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loan
  template:
    metadata:
      labels:
        app: loan
    spec:
      containers:
        - name: loan
          image: anthonysk/loan:0.0.1-SNAPSHOT
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8090
          envFrom:
            - configMapRef:
                name: loan-config
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 700Mi
          startupProbe:
            httpGet: { path: /actuator/health/liveness, port: http }
            periodSeconds: 5
            failureThreshold: 24
          readinessProbe:
            httpGet: { path: /actuator/health/readiness, port: http }
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /actuator/health/liveness, port: http }
            periodSeconds: 10

---

apiVersion: v1
kind: Service
metadata:
  name: loan
spec:
  type: LoadBalancer
  selector:
    app: loan
  ports:
    - name: http
      port: 8090
      targetPort: http
