name: configserver
deploymentName: configserver-deployment
replicaCount: 1

image:
  repository: anthonysk/configserver
  tag: 0.0.1-SNAPSHOT
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 8071
  targetPort: 8071
  nodePort: 30071

configMap:
  name: configserver-config
  data:
    HOME: "/tmp"
    JAVA_TOOL_OPTIONS: "-XX:MaxRAMPercentage=75 -Duser.timezone=Asia/Taipei"
    SPRING_RABBITMQ_HOST: "host.docker.internal"
    MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED: "true"

secret:
  name: microservices-secrets

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 700Mi
